# Generated by Django 3.0.8 on 2020-07-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
    ]
